on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 19 ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
      - name: build
        run: |
          mvn -B package
